### ISSUE TITLE
Config permissions issues

### ISSUE THREAD

**Issue by brittonhayes** [GGP1/kure#3]
# Description

Hey there! Really like the idea of kure and would love to use it. Unfortunately, when attempting to run `kure`, it appears that there are some issues with the permissions being set by the config file or even with the permissions schema deeming a config eligible for reading by `kure`. 

This prevents me from using any subcommands because the config is read before every function call. I cannot even run the help command, so I would consider this fairly high severity.

It looks as though this was also spotted in your Github action `build` step here:
https://github.com/GGP1/kure/runs/1980446702#step:4:87

# Expected Behavior

```shell
# Desired behavior is the following command
# followed by no error and a successfully created yaml config
kure config create
```

# System Details

```yaml
# Systems where the error 
# has been replicated
systems:
 - name: "Pop OS"
   shell: "zsh"
   prompt: "starship"

 - name: "OSX"
   shell: "zsh"
   prompt: "starship"
```

# Possible Issues

I believe the issue is localized to the `/config` package in the repository as that is the only place dealing with file permissions for `~/.kure/kure.*` files. 

# Screenshots
![image](https://user-images.githubusercontent.com/46035482/109361712-5720b980-783e-11eb-9fea-bb877c9da74b.png)
![image](https://user-images.githubusercontent.com/46035482/109361739-66a00280-783e-11eb-89ca-c069215fae1e.png)

**Comment by GGP1** [comment]
The configuration folder that contains the configuration file is created using the permission 0600, here's where it happens:

```go
if err := os.MkdirAll(home, 0600); err != nil {
	return errors.Wrap(err, "couldn't create the configuration directory")
}
```
and so is the file created with the `kure config create` file:

```go
if err := os.WriteFile(opts.path, bytes.ToLower(cfgContent), 0600); err != nil {
	return errors.Wrap(err, "writing configuration skeleton")
}
```

Please make sure the configuration file is created by the same user that access it. If you keep receiving the same error it could be changed as the configuration file does not contain sensitive information.

**Comment by GGP1** [comment]
```go
viper.SetConfigPermissions(0600)
```

The configuration file has the file permissions **0600** (only the owner can read/write it). Please make sure the configuration file is created by the same user that access it. If you keep receiving the same error it could be changed  to **0666** so any user can read/write to it as the configuration file does not contain sensitive information.

**Comment by GGP1** [comment]
It looks like Kure is not recognizing the configuration file, which is strange as you've created it and in the configuration the file permission are set to **0600**:

```go
viper.SetConfigPermissions(0600)
```

The directory used to store the default configuration and the `config command` also have the same permissions. I guess it could be fixed by changing them to **0666**, do you have any way of checking that? Thanks for pointing this out.

**Comment by brittonhayes** [comment]
Hey @GGP1! Thanks for the quick reply. Really appreciate it. 

So I've gone ahead and tried creating the config file again from `kure` as the user that owns the file, and I still seem to be running into the same issue. 

Is there something I should be doing differently here?

# Steps Taken

1. set `KURE_CONFIG="~/.config/kure.yaml"` in `~/.zshenv`
2. `chown` the config file then 
2. list out permissions of config to see that I do indeed own the file as my user
3. attempt to run `kure` now


# Screenshots and my config

```yaml
# Identitation must be respected and paths must be absolute. 
# In case any of these values is omitted, Kure will use the default one.
# See ../configuration.md for further information.
clipboard:
  timeout: "15s" # Set to "0s" or leave blank for no timeout
  
database:
  path: "/home/britton/.config/kure.db" # Must be absolute

editor: "micro"

session:
  prefix: "kure:~$"
  timeout: "10m"  # Set to "0s" or leave blank for no timeout
```

![image](https://user-images.githubusercontent.com/46035482/109367687-a4575800-784b-11eb-8a21-b76dddcd9888.png)

![image](https://user-images.githubusercontent.com/46035482/109367724-bc2edc00-784b-11eb-809f-38fc2e733457.png)
![image](https://user-images.githubusercontent.com/46035482/109367792-ebdde400-784b-11eb-94c5-f73a5c2957dc.png)

**Comment by GGP1** [comment]
It looks like there is nothing wrong, for some reason it's not recognizing the file although you are the owner. I will change the configuration file permissions to **0666**, that should solve it. However, Kure uses temporary file when editing records using the interactive mode (temporary files are created by the standard library with **0666** as well. Could you test creating a temporary file with go and run the program? You can simple do it by:

1. `touch main.go`
2. `code main.go`
3. Pasting this code
```go
f, err := os.CreateTemp("", "*."+ext)
if err != nil {
	return "", errors.Wrap(err, "creating temporary file")
}
f.Close()
```
4. `go run main.go`

if this returns the same error then it may be something else.

**Comment by brittonhayes** [comment]
Yeah absolutely! I can test that here in about an hour since I'm about to be hopping in the car for a bit.

Will report back any findings as soon as I get back to the computer. Thanks again for your responsiveness.

**Comment by brittonhayes** [comment]
Alright I've gone ahead and tried this and it created no error. I got a successful program exit. 

![image](https://user-images.githubusercontent.com/46035482/109375207-d1b5fd00-786f-11eb-93f8-b04eae4bce68.png)

**Comment by GGP1** [comment]
Kure uses viper to read the configuration which under the hood uses os.Open(). There shouldn't be any error, do you have `~.config` folder permissions?

**Comment by brittonhayes** [comment]
Yeah, I've got full read write permissions to my `~/.config` folder. That's what's really confusing me :confused:. It says I don't have permissions to the default `~/.kure/kure.yaml` file when I leave it as default as well.

Could this be related to this Github Actions run? The one function that failed was `get home directory`

https://github.com/GGP1/kure/runs/1980446702#step:4:87

**Comment by GGP1** [comment]
I'm not sure which permissions does the workflow setup has, it works well in both linux and windows. One solution could be cloning the repository and changing the permissions of the `config.go` file and overwrite the binary. But they are essentially executing functions from the standard library. If this solves the issue then it's something related to the permissions.

**Comment by brittonhayes** [comment]
I'll give that a shot! :crossed_fingers: Cloning now.

**Comment by fixxar1911** [comment]
I have this error as well both on pop!os install via make and macos install via brew

**Comment by GGP1** [comment]
It has to the the configuration files permissions then, @brittonhayes could you check that?

**Comment by GGP1** [comment]
It has to be the configuration files permissions then, @brittonhayes could you check that?

**Comment by fixxar1911** [comment]
Jupiter ❯ Projects git clone git@github.com:GGP1/kure.git
Cloning into 'kure'...
remote: Enumerating objects: 1256, done.
remote: Counting objects: 100% (1256/1256), done.
remote: Compressing objects: 100% (733/733), done.
remote: Total 1256 (delta 598), reused 1122 (delta 464), pack-reused 0
Receiving objects: 100% (1256/1256), 490.12 KiB | 1.84 MiB/s, done.
Resolving deltas: 100% (598/598), done.
Jupiter ❯ Projects ls -ld ~/.kure/*                      
zsh: no matches found: /home/fixxar/.kure/*
Jupiter ❯ Projects cd kure 
Jupiter ❯ kure (master) ✔ make install
Jupiter ❯ kure (master) ✔ kure ls
2021/02/26 21:13:41 stat /home/fixxar/.kure/kure.yaml: permission denied
Jupiter ❯ kure (master) ✔ ls -ld ~/.kure/*
zsh: no matches found: /home/fixxar/.kure/*
Jupiter ❯ kure (master) ✔ ls -ld ~/.kure/ 
drw------- 2 fixxar fixxar 4096 Feb 26 21:13 /home/fixxar/.kure/
Jupiter ❯ kure (master) ✔

**Comment by brittonhayes** [comment]
Looks like I don't have file or folder permissions to this. And it's like it doesn't change no matter what permissions changes I perform since the permissions are set prior to any operations that occur in the program.

I have the same results as @fixxar1911 above

![image](https://user-images.githubusercontent.com/46035482/109376148-6cfea080-7877-11eb-8283-3115cdcbb3a7.png)

**Comment by GGP1** [comment]
Try deleting the folder that was created by Kure in the first place and run any command again.

**Comment by fixxar1911** [comment]
Jupiter ❯ kure (master) ✔ ls -l ~/.kure/*
zsh: no matches found: /home/fixxar/.kure/*
Jupiter ❯ kure (master) ✔ ls -ld ~/.kure 
drw------- 2 fixxar fixxar 4096 Feb 26 21:13 /home/fixxar/.kure
Jupiter ❯ kure (master) ✔ rm -rf ~/.kure
Jupiter ❯ kure (master) ✔ ls -ld ~/.kure
ls: cannot access '/home/fixxar/.kure': No such file or directory
Jupiter ❯ kure (master) ✔ kure config create
2021/02/26 21:18:51 stat /home/fixxar/.kure/kure.yaml: permission denied
Jupiter ❯ kure (master) ✔ ls -ld ~/.kure    
drw------- 2 fixxar fixxar 4096 Feb 26 21:18 /home/fixxar/.kure
Jupiter ❯ kure (master) ✔ ls -l ~/.kure 
total 0
Jupiter ❯ kure (master) ✔

**Comment by brittonhayes** [comment]
> Try deleting the folder that was created by Kure in the first place and run any command again.

Here is the result of this:

![image](https://user-images.githubusercontent.com/46035482/109376320-86541c80-7878-11eb-8c87-889e31b85e29.png)

**Comment by GGP1** [comment]
Set `config.go` like this:

```go
package config

import (
	"os"
	"path/filepath"

	"github.com/pkg/errors"
	"github.com/spf13/viper"
)

// Load configuration file.
func Load() error {
	envPath := os.Getenv("KURE_CONFIG")

	switch {
	case envPath != "":
		ext := filepath.Ext(envPath)
		if ext == "" || ext == "." {
			return errors.New("\"KURE_CONFIG\" environment variable must have an extension")
		}

		viper.SetConfigType(ext[1:])
		viper.SetConfigFile(envPath)

	default:
		home, err := os.UserHomeDir()
		if err != nil {
			return errors.Wrap(err, "couldn't find the home directory")
		}
		home = filepath.Join(home, ".kure")

		if err := os.MkdirAll(home, 0666); err != nil {
			return errors.Wrap(err, "couldn't create the configuration directory")
		}

		configPath := filepath.Join(home, "kure.yaml")
		viper.SetConfigType("yaml")
		viper.SetConfigPermissions(0666)

		if _, err := os.Stat(configPath); err != nil {
			if os.IsNotExist(err) {
				setDefaults(filepath.Join(home, "kure.db"))
				if err := viper.WriteConfigAs(configPath); err != nil {
					return errors.Wrap(err, "couldn't write the configuration file")
				}
			} else {
				return err
			}
		}

		viper.SetConfigFile(configPath)
	}

	if err := viper.ReadInConfig(); err != nil {
		return errors.Wrap(err, "couldn't read the configuration")
	}

	if viper.InConfig("auth") {
		return errors.New("found invalid key in the configuration file: \"auth\"")
	}

	return nil
}

func setDefaults(dbPath string) {
	var defaults = map[string]interface{}{
		"clipboard.timeout": "0s",
		"database.path":     dbPath,
		"editor":            "vim",
		"keyfile.path":      "",
		"session.prefix":    "kure:~ $",
		"session.timeout":   "0s",
	}

	for k, v := range defaults {
		viper.SetDefault(k, v)
	}
}

```

remove the folder, compile and execute any command. If it doesn't work then I'm not sure it has to be with Kure.

**Comment by brittonhayes** [comment]
Yeah I ran `go run main.go` after replacing the config.go with this and same issue :confused:.

Do you think this could be a Viper problem with Go 1.16?

**Comment by GGP1** [comment]
I'm not sure since 1.16 was released the last week, it could be. One last shot, in the main file comment the config.Load func and hardcode the `dbPath` variable. If it works then it's something related to Viper. Like this:

```go
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	"github.com/GGP1/kure/commands/root"
	"github.com/GGP1/kure/config"
	"github.com/GGP1/kure/sig"

	"github.com/awnumar/memguard"
	"github.com/spf13/viper"
	bolt "go.etcd.io/bbolt"
)

func main() {
	// if err := config.Load(); err != nil {
		// log.Fatal(err)
	// }

	dbPath := path/to/a/file
	db, err := bolt.Open(dbPath, 0600, &bolt.Options{Timeout: 200 * time.Millisecond})
	if err != nil {
		log.Fatalf("couldn't open the database: %v", err)
	}

	// Listen for a signal to release resources and delete sensitive information
	sig.Signal.Listen(db)

	if err := root.Execute(db); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		db.Close()
		memguard.SafeExit(1)
	}

	db.Close()
	memguard.SafeExit(0)
}

```

**Comment by GGP1** [comment]
And also, make sure to run `go install .` and not `go run main.go` since it's not replacing the kure command.

**Comment by GGP1** [comment]
And also, make sure to run `go install .`. and not `go run main.go` since it's not replacing Kure's executable.

**Comment by brittonhayes** [comment]
```go
package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/GGP1/kure/commands/root"
	"github.com/GGP1/kure/sig"

	"github.com/awnumar/memguard"
	bolt "go.etcd.io/bbolt"
)

func main() {
	// if err := config.Load(); err != nil {
	// log.Fatal(err)
	// }

	db, err := bolt.Open("./test.db", os.ModeType, &bolt.Options{Timeout: 200 * time.Millisecond})
	if err != nil {
		log.Fatalf("couldn't open the database: %v", err)
	}

	// Listen for a signal to release resources and delete sensitive information
	sig.Signal.Listen(db)

	if err := root.Execute(db); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		db.Close()
		memguard.SafeExit(1)
	}

	db.Close()
	memguard.SafeExit(0)
}
```
This allowed it to run the program root command and get an output so that's a win!

The config is still not being read in but I at least got something back. Then it removes all permissions from my user for the test.db file

![image](https://user-images.githubusercontent.com/46035482/109376689-18f5bb00-787b-11eb-996c-ac56ce1803f1.png)
![image](https://user-images.githubusercontent.com/46035482/109376705-3460c600-787b-11eb-91a3-1316287e4869.png)
![image](https://user-images.githubusercontent.com/46035482/109376714-4e9aa400-787b-11eb-9d30-d67234900a43.png)

**Comment by brittonhayes** [comment]
> And also, make sure to run `go install .`. and not `go run main.go` since this last is not building Kure's executable.

Oops, just saw this.

**Comment by GGP1** [comment]
If it works then uncomment the config.Load() func and compile/execute again (it should work).

**Comment by brittonhayes** [comment]
Unfortunately, still no fix on the config permissions here. :confused: 

```go 
	if err := config.Load(); err != nil {
		log.Fatal(err)
	}

	db, err := bolt.Open("./test.db", os.ModeType, &bolt.Options{Timeout: 200 * time.Millisecond})
	if err != nil {
		log.Fatalf("couldn't open the database: %v", err)
	}
```

![image](https://user-images.githubusercontent.com/46035482/109376823-f912c700-787b-11eb-9f42-422627fe87fc.png)

**Comment by GGP1** [comment]
If the `config.go` file is using os.ModeType as well then it an issue related to viper.

**Comment by brittonhayes** [comment]
Yep, I set all of it to `os.ModeType` for a sanity check and it's still the case with that set. So I think you could be correct in the assumption that this is a viper issue. Unfortunately this Viper issue still does render the CLI temporarily unusable for my device until viper's permission quirk gets sorted out. :disappointed: 

I'll see if I can find any notes of this in their issues but I guess in the mean time, please definitely let me know if you find a source for this issue! I know it's a weird one, so sorry to fill your evening with bug hunting but thank you for taking the time to work through it. It really is appreciated and I'm sure will get worked out soon enough.

**Comment by GGP1** [comment]
Thank you and @fixxar1911 for your patience and time, if there isn't a solution soon I will try changing Kure's configuration. Again, thanks a lot.

**Comment by brittonhayes** [comment]
You bet. It's a great project and I'm looking forward to watching it grow. Holler if you need me to test any changes!

**Comment by GGP1** [comment]
Hi @brittonhayes  and @fixxar1911 , I've replaced Viper as they seem to be moving to a v2 version (release date unknown) and most of its dependencies aren't used in this project. 

If the problem persists it's directly related to Go's permissions and system calls, try running `kure` with `sudo` privileges. However, you shouldn't get this error if you are able to read and write to files that you create using Go and 0600 permissions. Please let me know if you try it.

**Comment by fixxar1911** [comment]
I was able to touch a file using go 

``package main

import (
    "fmt"
    "log"
    "os"
    "time"
)

func main() {
    fileName := "temp.txt"
    _, err := os.Stat(fileName)
    if os.IsNotExist(err) {
        file, err := os.Create("temp.txt")
        if err != nil {
            log.Fatal(err)
        }
        defer file.Close()
    } else {
        currentTime := time.Now().Local()
        err = os.Chtimes(fileName, currentTime, currentTime)
        if err != nil {
            fmt.Println(err)
        }
    }
}

**Comment by GGP1** [comment]
I've replicated the code in another repo to fix the build workflow (which returned exactly the same error) and it appears to be os.MdirAll(".kure", 0600). I will make sure it is that and fix it. @fixxar1911 ok, os.Create uses 0666 so changing permissions should solve it.

**Comment by GGP1** [comment]
I've replicated the code in another repo to fix the build workflow (which returned exactly the same error) and it appears to be `os.MdirAll(".kure", 0600)`. @fixxar1911 ok, os.Create uses 0666 so changing permissions should solve it.

**Comment by GGP1** [comment]
The issue is now fixed -> [v0.2.1](https://github.com/GGP1/kure/releases/tag/v0.2.1). It was quite confusing not receiving the error in some Linux distros nor Windows. Thanks for your help!

**Comment by brittonhayes** [comment]
I'll give this a test right now!

**Comment by fixxar1911** [comment]
confirmed working for me on pop!os I will wait for the brew update to try it on my mac.

**Comment by brittonhayes** [comment]
@fixxar1911 This might be a stupid question, but I'm still unable to get it to work on PopOS. Is there something I'm doing wrong here?

**Comment by GGP1** [comment]
@fixxar1911 Brew is already updated :thumbsup:

**Comment by brittonhayes** [comment]
@GGP1 The new release works for me. You're a hero and a scholar. Thanks for your effort, boss! :tada:

**Comment by GGP1** [comment]
You both helped me a lot, much thanks!! I'll keep trying to offer the best tool possible, feel free to drop new ideas/comments on the [discussions](https://github.com/GGP1/kure/discussions) section or open new issues.

**Comment by GGP1** [comment]
You both helped me a lot, much thanks!! I'll keep trying to offer the best tool possible, do not hesitate to drop new ideas/comments on the [discussions](https://github.com/GGP1/kure/discussions) section or open new issues.
